version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: libuser
      POSTGRES_PASSWORD: libpass1234
      POSTGRES_DB: libdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spring-net

networks:
  spring-net:
volumes:
  postgres_data:
  redis_data:
